### ISSUE TITLE
Models open ?

### ISSUE THREAD

**Issue by mserouar** [and-jonas/wheat-segmentation-models#1]
Will the models "segear_ff.pt," "segveg_ff.pt," and "segcol_rf.pkl" be available, at least the weights only for inference (not necessarily the raw data used) ?

**Comment by and-jonas** [comment]
Please find a link to the data sets and a google drive repository containing the trained models (.pt and .pkl) in the updated readme file. 
Hope this works,

**Comment by mserouar** [comment]
Many thanks !

**Comment by mserouar** [comment]
Just in case, I faced some issues (not a big deal), here : 

- **Specify scikit version to avoid issues with pickle loading** : `pip install scikit-learn==1.2.2`

- **Mask format, right after save_output** : `ear_mask = ear_mask.astype(np.uint8)` and `veg_mask = veg_mask.astype(np.uint8)`
